### PR TITLE
Different API for plurals

### PR DESCRIPTION
**Pull request by mieszkosabo**
Hey @QuiiBz , I've been thinking about #44 and I thought that maybe we should change the API for plurals all together. As you mentioned, it is tricky to get correct types form the syntax you proposed. Another issue is that, in my opinion, the syntax is hard to understand. Especially that people who create these translations and copy could be PMs, designers, translators and other non-technical people.

So I got inspired by how it is solved in I18n-next and imo this API is both easy to understand and pretty easy to make type-safe as well!

with such translations:

```ts
{
  thing_zero: 'No things',
  thing_one: 'One thing',
  thing_other: '{count} {adjective} things',
}
```

we can use do:

```ts
t('thing', { count: 1, adjective: 'cool' })
```

So `thing_zero`, `thing_one` and `thing_other` will have a single type of `thing` and it will get a `count` param, which is used to decide which variant to use.

Another advantage of this is that under the hood it will use `Intl.PluralRules` which can pick correct variant for all languages. Because the current implementation would only work for some languages. For example you can't correctly do Polish translations with API that makes you explicitly write all cases such as (=1, =2, etc) because the rules are more complex.

Please don't look at the code, it is very rough, I will refactor it if you would like this PR to be merged.

One other thing I consider is also, whether to use `_` as a separator or maybe something like `:`, because I can imagine people using `_` in their translations, esp. if they use snake_case. 

Thanks

### CODE REVIEW

**Comment by QuiiBz** [comment]
Thanks for the detailed explanation. This is something I would like to have on next-international (& international-types).

I'm not sure about the `_` delimiter, you mentioned some edge cases and I agree. Using `:`, `#`, or `@` seems like a better option, because no one (I hope) will use these characters in a translation key. I'm also wondering about the count identifier: we could also use numbers and keep `other` for everything else:

```ts
// With numbers and :
export const en = {
  'user.requests:0': 'You made 0 requests this month',
  'user.requests:1': 'You made 1 request this month',
  'user.requests:other': 'You made {requests} requests this month',
}
// Without numbers and :
export const en = {
  'user.requests:zero': 'You made 0 requests this month',
  'user.requests:one': 'You made 1 request this month',
  'user.requests:other': 'You made {requests} requests this month',
}
// With numbers and #
export const en = {
  'user.requests#0': 'You made 0 requests this month',
  'user.requests#1': 'You made 1 request this month',
  'user.requests#other': 'You made {requests} requests this month',
}
// Without numbers and #
export const en = {
  'user.requests#zero': 'You made 0 requests this month',
  'user.requests#one': 'You made 1 request this month',
  'user.requests#other': 'You made {requests} requests this month',
}
// With numbers and @
export const en = {
  'user.requests@0': 'You made 0 requests this month',
  'user.requests@1': 'You made 1 request this month',
  'user.requests@other': 'You made {requests} requests this month',
}
// Without numbers and @
export const en = {
  'user.requests@zero': 'You made 0 requests this month',
  'user.requests@one': 'You made 1 request this month',
  'user.requests@other': 'You made {requests} requests this month',
}
```

I don't know which one I like the best.

**Comment by mieszkosabo** [comment]
Thanks for your feedback, that's great to hear that you're on board with this idea!

About the delimiter, i kind of like the `#` as it has some connections to numbers and counting and also it is unlikely to be used in a normal translation key.

About the count identifiers: I took `'zero' | 'one' | 'two' | 'few' | 'many' | 'other'` from the I18n standard, these are the ones that cover all languages. 0,1 and other work in English, but in other languages, like eg. most slavic ones that's not enough.
Check this out:

CleanShot 2023-04-22 at 10 28 57@2x

So for example a word "cow" would have to be written like this in `pl.ts`:

```ts
{
  cow#zero: 'Zero krów',
  cow#one: 'Jedna krowa',
  cow#few: '{count} krowy',
  cow#many: '{count} krów',
  cow#other: '{count} krowy',
}
```

Unless, apart from these standard categories such as `'zero' | 'one' | 'two' | 'few' | 'many' | 'other'` we could also allow for keys like:

```ts
{
  cow#zero: 'Zero krów',
  cow#one: 'Jedna krowa',
  cow#few: '{count} krowy',
  cow#many: '{count} krów',
  cow#other: '{count} krowy',
  cow#6: 'Some specific message for count equal to 6 here',
}
```

But maybe this could be done as a separate feature.

Let me know what do you thing about it

**Comment by QuiiBz** [comment]
For now, we can go with the standard `'zero' | 'one' | 'two' | 'few' | 'many' | 'other'`, we can work on supporting arbitrary numbers later.

I also like `#` as a delimiter, and I think it should be possible to provide autocompletion (or at least type safety) to the keys, such as we can't have invalid keys.

**Comment by mieszkosabo** [comment]
Hey @QuiiBz, I refactored the solution so it's ready to be reviewed 👍 

I have one problem though, I wanted to test plurals in `examples`, but I can't run it:

CleanShot 2023-04-26 at 14 45 45

Have you encountered such issue? I don't think I changed any workspace config. Just run `pnpm dev` inside `examples/next` dir.

**Comment by QuiiBz** [comment]
Hi @mieszkosabo, I'm looking back at this PR and would love to get this feature supported. Would you like to resolve the merge conflicts? We have made quite a few changes since this PR has been created.

**Comment by QuiiBz** [comment]
Closing this PR as stale. I've created #75 to support this amazing feature, which is heavily based on this PR. Thanks!

**Comment by mieszkosabo** [comment]
Hey, sorry for long time not responding, been pretty busy. I'm so glad that this feature eventually found its way into the repo and I happy that I could be of a help!

**Pull request closed without merging**
