### PR TITLE
chore(docs): add bun installation support

### PR DESCRIPTION
**Pull request by poypoydev**
I thought it would be useful for people to also know you can install this library without any problems using bun, Vercel also supports bun installation now, so I think its handy to also have it as an option.

### CODE REVIEW

**Review by QuiiBz — CHANGES_REQUESTED** [review]
Thanks! Could you revert the formatting changes?

**Comment by poypoydev** [comment]
Should be fixed now!

**Comment by poypoydev** [comment]
Prettier edit on save absolutely not saving the day *again*... Should all be fixed now!

**Review by QuiiBz — APPROVED** [review]
Thanks!

**Pull request merged**
